service: appsync-pagination-dynamodb
frameworkVersion: "3"
configValidationMode: error

plugins:
  - serverless-appsync-plugin
  - serverless-iam-roles-per-function

provider:
  name: aws
  region: us-west-2

custom:
  tableName: library-${sls:stage}

appSync:
  name: pagination-dynamodb-api
  schema:
    - schema/*.graphql
  logging:
    level: ERROR
  authentication:
    type: API_KEY
  apiKeys:
    - name: myApiKey
  
  dataSources:
    paginatorFunction:
      type: AWS_LAMBDA
      config:
        functionName: listBooksPaginated

  resolvers:
    Query.listBooks:
      functions:
        - dataSource: paginatorFunction
          code: src/resolvers/listBooks.js

functions:
  listBooksPaginated:
    handler: src/listBooksHandler.handler
    environment:
      TableName: ${self:custom.tableName}
      Region: ${self:provider.region}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource:
          - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tableName}"

resources:
  Resources:
    Library:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH